[project]
name = "atlas"
version = "0.1.0"
description = "Training metrics tracker for ML"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["logging>=0.4.9.6", "websockets>=15.0.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
