[project]
name = "atlas-dashboard"
version = "0.1.0"
description = "connects to the atlas dashboard and provides metrics"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "websockets>=15.0.1",
]
